"""Renamed producrts name in category r/n

Revision ID: e6448fb8ac52
Revises: aed5a7ff1408
Create Date: 2026-03-13 16:49:25.648819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6448fb8ac52'
down_revision: Union[str, Sequence[str], None] = 'aed5a7ff1408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
